### ISSUE TITLE
/listportals Is not in /help

### ISSUE THREAD

**Issue by SirJosh3917** [Tunous/EverybodyEditsProtocol#12]
Title

Also, why do we have /listportals?

I also noticed that /listportals works in not my world (ninjasupeatsninjabot's Color Wash [!ON!], it is owned by a crew called Gears, of which I am in. (but i made the bot as well as the acc) )

**Comment by SirJosh3917** [comment]
Nevermind, /listportals does show up.

**Comment by Tunous** [comment]
`/listportals` was made to make it easy to find what portal ids are used in world and where all portals are located. 

As far as I remember it is available to anyone who has edit. That's why you could use it as crew member.
