### ISSUE TITLE
Update: Update Shop.md to latest packages

### ISSUE THREAD

**Issue by SirJosh3917** [Tunous/EverybodyEditsProtocol#16]
You last edited Shop.md **6 months ago**. I'm sure there's plenty that's been added by now.

**Comment by Tunous** [comment]
I am aware of that but don't plan on updating it myself. It's just an additional information contributed to this repository which I said I won't be managing. 

There is a plan to keep it generated from the Unity EE version automatically as partly mentioned in https://github.com/Tunous/EverybodyEditsProtocol/issues/3#issuecomment-241681773 but I decided to not use it before Unity EE is released. That sadly didn't happen yet and probably won't happen soon :( 

If you want to contribute I'll gladly accept pull requests.
