### ISSUE TITLE
Suggestion: use tables

### ISSUE THREAD

**Issue by Decagon** [Tunous/EverybodyEditsProtocol#4]
Using tables instead of lists will increase readability. For example, https://github.com/Medium/medium-api-docs

Here's what using tables might look like:

| Type | Event Name | Description |
| ------- | ---------------- | --------------- |
`[0] Integer` | Player Id | The player's id. |
`[1] Integer` | Gold Coins | The amount of collected gold coins. |
`[2] Integer` | Blue Coins| The amount of collected blue coins.|
`[3] UInt` | X | The x-coordinate of the coin's position. |
`[4] UInt` | Y | The y-coordinate of the coin's position. |

**Comment by Tunous** [comment]
Interesting idea. I didn't think of using tables before but it indeed looks much better. 

What about this format:

| Id | Type | Name | Description |
|---|------|-------|-------------|
| `0` | `Integer` | Player Id | The player's id. |
| `1` | `Integer` | Gold Coins | The amount of collected gold coins. |
| `2` | `Integer` | Blue Coins| The amount of collected blue coins.|
| `3` | `UInt` | X | The x-coordinate of the coin's position. |
| `4` | `UInt` | Y | The y-coordinate of the coin's position. |

**Comment by Decagon** [comment]
That looks much better (as it now clearly shows the id for the array.) I'll start converting the tables now into that format.

**Comment by Tunous** [comment]
Ok great :smile:

**Comment by Tunous** [comment]
Added with #5.
